config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :categories do
    get :courses, on: :member
  end
  resources :verticles do
    get :categories, on: :member
  end
  root to: 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :verticle
  has_many :courses
  validates_uniqueness_of :name
  after_create :send_email
  private
  def send_email
    UserMailer.new_record.deliver_now
  end
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :category
  validates_uniqueness_of :name
  after_create :send_email
  private
  def send_email
    UserMailer.new_record.deliver_now
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable ,:omniauthable, omniauth_providers: [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

end

app/models/verticle.rb
class Verticle < ApplicationRecord
  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protected
  def authenticate_user!
    redirect_to root_path, notice: "You must login" unless user_signed_in?
  end

  def after_sign_in_path_for(resource)
    verticles_path || root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy, :courses]
  before_action :authenticate_user!
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # GET /categories/1/courses.json
  def courses
    @courses = @category.courses.paginate(page: params[:page], per_page: 10)
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :state, :verticle_id)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :state, :author, :category_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/verticles_controller.rb
class VerticlesController < ApplicationController
  before_action :set_verticle, only: [:show, :edit, :update, :destroy, :categories]
  before_action :authenticate_user!
  # GET /verticles
  # GET /verticles.json
  def index
    @verticles = Verticle.includes(:categories).all
  end

  # GET /verticles/1
  # GET /verticles/1.json
  def show
  end

  # GET /verticles/new
  def new
    @verticle = Verticle.new
  end

  # GET /verticles/1/edit
  def edit
  end

  # GET /verticles/1/categories.json
  def categories
    @categories = @verticle.categories.paginate(page: params[:page], per_page: 10)
  end

  # POST /verticles
  # POST /verticles.json
  def create
    @verticle = Verticle.new(verticle_params)

    respond_to do |format|
      if @verticle.save
        format.html { redirect_to @verticle, notice: 'Verticle was successfully created.' }
        format.json { render :show, status: :created, location: @verticle }
      else
        format.html { render :new }
        format.json { render json: @verticle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /verticles/1
  # PATCH/PUT /verticles/1.json
  def update
    respond_to do |format|
      if @verticle.update(verticle_params)
        format.html { redirect_to @verticle, notice: 'Verticle was successfully updated.' }
        format.json { render :show, status: :ok, location: @verticle }
      else
        format.html { render :edit }
        format.json { render json: @verticle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verticles/1
  # DELETE /verticles/1.json
  def destroy
    @verticle.destroy
    respond_to do |format|
      format.html { redirect_to verticles_url, notice: 'Verticle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_verticle
      @verticle = Verticle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def verticle_params
      params.require(:verticle).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/verticles_helper.rb
module VerticlesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.check_box :state %>
  </div>

  <div class="field">
    <%= form.label :verticle_id %>
    <%= form.text_field :verticle_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/courses.html.erb
<h1>Home#index</h1>
<%= javascript_pack_tag 'index_view' %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>State</th>
      <th>Verticle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.state %></td>
        <td><%= category.verticle_id %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>State:</strong>
  <%= @category.state %>
</p>

<p>
  <strong>Verticle:</strong>
  <%= @category.verticle_id %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.check_box :state %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>State</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.state %></td>
        <td><%= course.category_id %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>State:</strong>
  <%= @course.state %>
</p>

<p>
  <strong>Category:</strong>
  <%= @course.category_id %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/home/index.html.erb
<div class="container">
  <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Passion</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/verticles">Passion</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <% if current_user.present?%>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/verticles/new">New Verticle <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/categories/new">New Category <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/courses/new">New Courses <span class="sr-only">(current)</span></a>
          </li>
        </ul>
      <% end %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto"></ul>
        <form class="form-inline my-2 my-lg-0">
          <% if current_user.present?%>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger my-2 my-sm-0" %>
          <%end%>
        </form>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/verticles/_form.html.erb
<%= form_with(model: verticle, local: true) do |form| %>
  <% if verticle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(verticle.errors.count, "error") %> prohibited this verticle from being saved:</h2>

      <ul>
        <% verticle.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/verticles/categories.html.erb
<h1>Home#index</h1>
<%= javascript_pack_tag 'index_view' %>

app/views/verticles/edit.html.erb
<h1>Editing Verticle</h1>

<%= render 'form', verticle: @verticle %>

<%= link_to 'Show', @verticle %> |
<%= link_to 'Back', verticles_path %>

app/views/verticles/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>Verticles</h1>
  <%= javascript_pack_tag 'collapsable_list' %> 
</div>

app/views/verticles/new.html.erb
<h1>New Verticle</h1>

<%= render 'form', verticle: @verticle %>

<%= link_to 'Back', verticles_path %>

app/views/verticles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @verticle.name %>
</p>

<%= link_to 'Edit', edit_verticle_path(@verticle) %> |
<%= link_to 'Back', verticles_path %>